### Registrar un usuario nuevo
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "nombre": "wilson",
    "correo": "prueba@gmail.com",
    "contrasena": "password"
}


### Hacer login con un usuario existente
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "correo": "prueba@gmail.com",
    "contrasena": "password"
}


### Acceder a todas las publicaciones
GET http://localhost:3000/api/publicaciones?pag=2

### Ver una publicacion especifica
GET http://localhost:3000/api/publicaciones/69db0d58-7d5d-41b5-a60f-04e142a9e93d

### Crear una publicacion
POST http://localhost:3000/api/publicaciones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvX2lkIjoiYjY5YTI4ZmQtYTAwOS00MzUzLWE3N2EtZTNhMzEzZTA4OTZlIiwiaWF0IjoxNzU0OTQwOTcyLCJleHAiOjE3NTQ5ODQxNzJ9.IhLdA8Nbt4fS4Hdd63xHRY3pFpFu4-DXhOHFH6dmFp8

{ 
    "titulo": "Mi nombre",
    "contenido": "Me llamo wilson"
}

